name: Shulker
version: ${version}
authors: ${authors}
description: An API to links NMS and make things easier.

main: org.shulker.spigot.ShulkerSpigotPlugin
load: startup

permissions:
  shulker.*:
    default: op
    children:
      shulker.reload: true
      shulker.commands.help: true
      shulker.commands.libraries: true
  shulker.reload:
    description: Allows to reload Shulker.
    default: op